### ISSUE TITLE
4.2.0 version is incompatible with flutter 3.13

### ISSUE THREAD

**Issue by TatsuUkraine** [daegalus/dart-uuid#101]
`meta` deps in the most recent release of uuid package conflicts with flutter stable (3.13 currently)

```log
Because every version of flutter_test from sdk depends on meta 1.9.1 and uuid >=4.2.0 depends on meta ^1.11.0, flutter_test from sdk is incompatible with uuid >=4.2.0.
So, because ... depends on both uuid ^4.2.0 and flutter_test from sdk, version solving failed.
```

**Comment by VagnerWillian** [comment]
@TatsuUkraine 

For now you can use

dependency_overrides:
   target: ^1.11.0

that will work

**Comment by daegalus** [comment]
All set, thanks for reporting it. 4.2.1 should have the lower version constraint.

**Comment by TatsuUkraine** [comment]
Thank you!
