### ISSUE TITLE
4.3.1 version is incompatible with flutter 3.16

### ISSUE THREAD

**Issue by boldt** [daegalus/dart-uuid#107]
It's basically the same as in https://github.com/daegalus/dart-uuid/issues/101, but with flutter 3.16:

> Because every version of flutter_test from sdk depends on meta 1.10.0 and uuid >=4.3.0 depends on meta ^1.11.0, flutter_test from sdk is incompatible with uuid >=4.3.0.
> So, because app depends on both uuid 4.3.1 and flutter_test from sdk, version solving failed.

**Comment by blondie63** [comment]
So do we have to wait for a next version of Flutter SDK?

**Comment by daegalus** [comment]
Sorry for the delay, busy with newborn still. 

I can rollback the meta version to fix this, my apologies, I was hasty to bump the version all the way.

**Comment by daegalus** [comment]
4.3.2 should fix this. please reopen if it doesnt
