### ISSUE TITLE
A bug in generateInternal() method in MathRNG class

### ISSUE THREAD

**Issue by showband** [daegalus/dart-uuid#110]
The method generateInternal() in MathRNG class does not work correctly when the initial seed is explicitly specified for MathRNG - it always generates the same random number over and over. The reason is the Random() is always created from scratch with the given seed - thus generating the same random number.

Here is my fix:
https://github.com/showband/dart-uuid/blob/main/lib%2Frng.dart#L27-L46

I forked your repository, fixed it and created a pull request.

Please consider merging into the uuid package for everyone to benefit.

**Comment by daegalus** [comment]
thank you for finding this and fixing it. ill make a new release once i run and fix tests

**Comment by daegalus** [comment]
The fix is now part of the v4.4.0 release, sorry for the delay, there were other problems I had to fix due to the change.
