### ISSUE TITLE
Duplicate values for UUIDv4

### ISSUE THREAD

**Issue by Mr-Pepe** [daegalus/dart-uuid#118]
I am getting duplicate values for UUIDv4 and I am pretty sure that I am doing something wrong, I just don't know what.

My Flutter web app collects anonymous analytics and creates a UUID for each started session. The analytics class looks something like this:

```dart
class Analytics {
  Analytics() : sessionId = Uuid(goptions: GlobalOptions(CryptoRNG())).v4();

  final String sessionId;

  Future<void> logEvent(String name) async {
    await (await getSupabaseClient()).from(analyticsEventTable).insert({
      'session_id': sessionId,
      'event_name': name,
    });
  }
}
```

The analytics class gets instantiated on app startup and a `session_started` event gets logged. However, I am getting duplicate entries in my database:

![image](https://github.com/daegalus/dart-uuid/assets/26527091/343bd882-a649-4afc-bc48-46fede01c4a5)

There are only a few dozen sessions logged so far, so I find it very surprising that there are collisions. 

Is this not the intended use case for this library?

**Comment by Mr-Pepe** [comment]
It seems that the same UUID keeps popping up every now and then:
![image](https://github.com/daegalus/dart-uuid/assets/26527091/5746f3ed-2caf-4400-9f6d-6a0d960e40c0)

**Comment by daegalus** [comment]
So I created a test script and emulated your example:

```dart
import 'package:uuid/data.dart';
import 'package:uuid/uuid.dart';
import 'package:uuid/rng.dart';

void main() {
  var blah = Analytics();
  blah.logEvent('test');
  blah.logEvent('test2');
}

class Analytics {
  Analytics() : sessionId = Uuid(goptions: GlobalOptions(CryptoRNG())).v4();

  final String sessionId;

  Future<void> logEvent(String name) async {
    print("Logging event $name with session $sessionId");
  }
}
```

Which gives me this output:
```sh
❯ dart run example/example.dart
Logging event test with session 447ccc50-edbb-4bd0-a446-15e455f5e36a
Logging event test2 with session 447ccc50-edbb-4bd0-a446-15e455f5e36a
```

Them both being the same in this case makes sense. So I have some follow up questions:

1. Does each event need a unique session id?
2. Are you creating a new Analytics instance for each event?
3. If you are doing a session per user, are you creating or recreating the analytics object for each user?

The reason I ask, is what you are doing is you are generating a single session id, saving it into sessionid, and then logging events for that session id. The session id is never regenerated.

If you need a unique session id for every event, you need to make one of the following changes:

- change `sessionID` to something like `internalUUID`, and save the entire UUID instantiation there (don't call v4()
  - Once you do that, you call `internalUUID.v4()` on every event to make a new uuid.
- Alternatively, is instantiate and generate a UUID in the event function. But that seems like a waste allocations and memory.

Try the following and let me know if it works for what you need:

```dart
class Analytics {
  Analytics() : internalUUID = Uuid(goptions: GlobalOptions(CryptoRNG()));

  final Uuid internalUUID;

  Future<void> logEvent(String name) async {
    print("Logging event $name with session ${internalUUID.v4()}");
  }
}
```

Output:
```sh
❯ dart run example/example.dart
Logging event test with session cf9b6124-1f5e-4adc-92dd-20f48951bb33
Logging event test2 with session 273ffa25-0b7b-4593-a7fd-efb09a6696e9
```

**Comment by daegalus** [comment]
Ok, I reread your thing, maybe you are doing it correct. But mine changes every time i run the example script.

So, my thoughts is the CryptoRNG() source is not working right and giving the same seed? can you do a similar test with the MathRNG class (aka default, so no rng passed in). Trying to deduce if maybe flutter or the device you are testing on isn't seeding things right.

**Comment by Mr-Pepe** [comment]
Thank you for the reply :)

Your first code snippet represents pretty well what I am doing. I only instantiate the analytics class once on app startup and then log events for that session. 

The MathRNG class had the same problem, which is why I moved to CryptoRNG.

I have not been able to reproduce the issue locally but it appears consistently in production, even after deploying several new versions of the app over the past couple of days. Interestingly, it is always the same UUID that has duplicates.

There were new duplicates yesterday/today:

![image](https://github.com/daegalus/dart-uuid/assets/26527091/1ea60fa8-92b0-4f61-9b5b-68525c3399d5)

In a first step I just wanted to confirm that I am not using the library in an unsupported way. With just 10 sessions per day, I am very surprised that these collisions happen.

**Comment by Mr-Pepe** [comment]
The source files for my web app are served via the Cloudflare CDN and get cached. I don't know how Dart and this library seed their RNG but is that something that might have an influence?

**Comment by daegalus** [comment]
> The source files for my web app are served via the Cloudflare CDN and get cached. I don't know how Dart and this library seed their RNG but is that something that might have an influence?

No, it seems you are running it right, but something is going wrong.

You mention webapp. Does that mean it's being transpiled to JavaScript? Trying to think what the RNG sources are there.

I have other users using this on web. And ive compiled and run my example file on web too. 

Is the analytics object or session ID being saved to local storage or anything on the web?

CDN caching shouldn't affect anything as the code is executed, you aren't storing static values.

Sorry for all the questions, trying to pin point what's happening.

Any chance you can add a bit of debug or console printing to see various state?

Like if the class is being recreated. 

I had requests to make it a const class in the past, so it's mostly a const class, maybe the staticness of that is failing. 

Another thing to try is expand the constructor into a full constructor, and save each object into a variable so you can debug what's happening at each step.

The crypto RNG, the UUID object, the session ID.

Another test ,is use MathRNG but pass a secure random seed into it using random.secure(), directly in the constructor.

Let me know if anything changes. You should most definitely be getting different values for each session. So its either the JS conversion breaking, or the seed.

I'll dig into how random works in browsers for Dart

**Comment by Mr-Pepe** [comment]
> Sorry for all the questions, trying to pin point what's happening.

No worries, I am very impressed by your responsiveness :slightly_smiling_face: 
The same session ID kept popping up, so I eventually switched to letting Supabase create the session ID for me when I log a new session start. 

> Does that mean it's being transpiled to JavaScript?

Yes.

> Is the analytics object or session ID being saved to local storage or anything on the web?

No, it's ephemeral. I have been wondering whether refreshing the app in the browser or navigating back and worth via the browser's back button might cause this. But that doesn't really make sense considering how far apart in time the duplicate session IDs are. 

> CDN caching shouldn't affect anything as the code is executed, you aren't storing static values.

I would also have been surprised if that was the case.

> Any chance you can add a bit of debug or console printing to see various state?
   Like if the class is being recreated.
   I had requests to make it a const class in the past, so it's mostly a const class, maybe the staticness of that is failing.
   Another thing to try is expand the constructor into a full constructor, and save each object into a variable so you can debug what's happening at each step.
   The crypto RNG, the UUID object, the session ID.

I couldn't reproduce locally, so I didn't really know how to approach this.

> Another test ,is use MathRNG but pass a secure random seed into it using random.secure(), directly in the constructor.

Sorry, I went a different route, letting my database generate the UUID instead. 

I still can not shake the feeling that the error is somehow on my side. In theory, anybody could extract my database API key from the browser and start sending random stuff to the database, but I don't know how likely that is, considering the very low number of users so far.

If I find the time, I'll reintroduce the previous logging using `uuid` and just dump session IDs into a debug table and see if duplicates pop up.

Thank you for you rhelp!

**Comment by kealist** [comment]
If you were using WASM build, there is this issue

https://github.com/dart-lang/sdk/issues/56609

**Comment by Rexios80** [comment]
This person was using CryptoRNG already
