### ISSUE TITLE
Same UUIDs generated every run when compiled to WASM

### ISSUE THREAD

**Issue by Rexios80** [daegalus/dart-uuid#125]
The same UUIDs are generated in the same order every run when compiled to WASM

See the sample here: https://github.com/Rexios80/uuid_wasm_test

**Comment by Rexios80** [comment]
I think this might only affect v4, but I'm not sure

**Comment by kealist** [comment]
This is the underlying issue.

https://github.com/dart-lang/sdk/issues/56609

**Comment by Rexios80** [comment]
This is a catastrophic issue that should be fixed and cherry-picked ASAP. Anyone generating UUIDs in Flutter web WASM apps could be unintentionally generating UUID collisions and lose a lot of data.

**Comment by daegalus** [comment]
4.5.0 is published
