### ISSUE TITLE
Removal of `UuidValue.nil`, get a const nil UUID

### ISSUE THREAD

**Issue by sbordeyne** [daegalus/dart-uuid#127]
With the latest version of this library, the `UuidValue.nil` constant has been deprecated, in favor of using `Namespace.nil.uuidValue`, but this change also implies that the expression is not const anymore.

Solutions:

- Keep `UuidValue.nil` as a const constructor to `UuidValue` and remove the deprecation flag
- Find a way to make `Namespace.nil.uuidValue` constant (I don't think it's possible though)
- Add a const constructor to UuidValue `fromNamespace` to generate an UuidValue from the namespace enum

For now, the only workaround I have to circumvent the deprecation warning and keep my constant uuids is to manually generate them with `const nilUuid = UuidValue.raw("00000000-0000-0000-0000-000000000000")` which is not ideal

Implementation of `fromNamespace` could look like:

```dart
  const UuidValue.fromNamespace(Namespace ns) :
    uuid = ns == Namespace.nil || ns == Namespace.NIL ?
      "00000000-0000-0000-0000-000000000000" :
        ns == Namespace.dns || ns == Namespace.DNS ?
          "6ba7b810-9dad-11d1-80b4-00c04fd430c8" :
            ns == Namespace.url || ns == Namespace.URL ?
              "6ba7b811-9dad-11d1-80b4-00c04fd430c8" :
                ns == Namespace.oid || ns == Namespace.OID ?
                  "6ba7b812-9dad-11d1-80b4-00c04fd430c8" :
                    ns == Namespace.x500 || ns == Namespace.X500 ?
                      "6ba7b814-9dad-11d1-80b4-00c04fd430c8" :
                        ns == Namespace.max || ns == Namespace.MAX ?
                          "ffffffff-ffff-ffff-ffff-ffffffffffff" :
                            "00000000-0000-0000-0000-000000000000"; // can't throw an exception here otherwise it's not constant anymore
```

**Comment by bymoye** [comment]
Hey, I don't understand what your purpose is, can you provide an application example?
If you just want to get the corresponding string UUID, you can use `Namespace.nil.value`

**Comment by bymoye** [comment]
Maybe you want: https://github.com/dart-lang/language/issues/2780

**Comment by sbordeyne** [comment]
Indeed, that's the feature I need.

The use case is to have my UUIDs be able to default to the nil UUID in case I don't specify one.

**Comment by daegalus** [comment]
Sorry for the delay. I think I will do the 3rd option with FromNamespace. That feels the least intrusive way to provide you what you need without breaking others. There are a lot of users of this library, and I have to balance needs versus not breaking others.

I will try to get a new version up today with the changes.

**Comment by daegalus** [comment]
Ok, I uploaded 4.5.1 with `fromNamespace` using a mostly similar block of code as you provided. I just didn't like duplicating the strings, so I found a way to keep it all coming from 1 source. Give it a go, and let me know if you have any other issues and we can reopen this or start a new one.

**Comment by bymoye** [comment]
> Ok, I uploaded 4.5.1 with `fromNamespace` using a mostly similar block of code as you provided. I just didn't like duplicating the strings, so I found a way to keep it all coming from 1 source. Give it a go, and let me know if you have any other issues and we can reopen this or start a new one.

Hey, wouldn't it be better to write it like this?
```
  UuidValue get uuidValue => switch (this) {
        nil || NIL => const UuidValue.raw(InternalConstants.zNIL),
        dns || DNS => const UuidValue.raw(InternalConstants.zDNS),
        url || URL => const UuidValue.raw(InternalConstants.zURL),
        oid || OID => const UuidValue.raw(InternalConstants.zOID),
        x500 || X500 => const UuidValue.raw(InternalConstants.zX500),
        max || MAX => const UuidValue.raw(InternalConstants.zMAX),
      };
```
Let Dart solve the rest.

**Comment by daegalus** [comment]
> > Ok, I uploaded 4.5.1 with `fromNamespace` using a mostly similar block of code as you provided. I just didn't like duplicating the strings, so I found a way to keep it all coming from 1 source. Give it a go, and let me know if you have any other issues and we can reopen this or start a new one.
> 
> Hey, wouldn't it be better to write it like this?
> ```
>   UuidValue get uuidValue => switch (this) {
>         nil || NIL => const UuidValue.raw(InternalConstants.zNIL),
>         dns || DNS => const UuidValue.raw(InternalConstants.zDNS),
>         url || URL => const UuidValue.raw(InternalConstants.zURL),
>         oid || OID => const UuidValue.raw(InternalConstants.zOID),
>         x500 || X500 => const UuidValue.raw(InternalConstants.zX500),
>         max || MAX => const UuidValue.raw(InternalConstants.zMAX),
>       };
> ```
> 
> Although deprecation warnings are used, there will still be people who use deprecated properties because they did not change in time, right?
> In this case, the uppercase enumeration will become `InternalConstants.zNIL`, which is a difficult trade-off.
> Is this a bug? Not sure. Consider it a known issue.
> 
> Let Dart solve the rest.

My thought was that if they are using a new feature, they are already upgrading their code to use it, so they can take the extra few seconds to lowercase their enums. 

But if you think it will cause problems for s lot of people, I can expand it. But that means anyone using the new function, will get depreciation warnings, even if they use the new value.

Maybe the better approach is to at least document that it only works with lowercase enums?

You are also correct on the switch statement, that is better. I was low on free time and just copy and pasted the fromNamespace one effectively. The const part doesn't make it const until there is a language change, but figured I'd get a head start.

If anyone thinks these are serious issues, I can revert uuidValue to be just `UuidValue.raw(value)` like it used to be. And I can add the deprecated values to the switches and branches.
