### ISSUE TITLE
Add convenient getters to the UUIDValue class to check the version of the UUID

### ISSUE THREAD

**Issue by sbordeyne** [daegalus/dart-uuid#128]
Bit of a weird feature request since it's already kinda possible, but the idea would be to add `isV1`, `isV3` getters (and so on for every UUID version) that would just do `this.version == x`.

This would be to make it in line with how dart does things (for instance with the List class, which has `isEmpty` / `isNotEmpty` getters instead of relying on length comparisons)

**Comment by daegalus** [comment]
Should be straight forward, I can add this

**Comment by daegalus** [comment]
I have added `isV#()`, `isNIL()` and `isMAX()` functions to UUIDValue in 4.5.1
