### ISSUE TITLE
JavaScript Performance

### ISSUE THREAD

**Issue by kostaa** [Daegalus/dart-uuid#17]
There is a substantial performance degradation once the dart code is compiled into javascropt. To generate some 1,800 UUIDs (v4) in dart it takes ~ 2 seconds. The same code in javascript takes over 50 seconds.

**Comment by Daegalus** [comment]
I'll take a look when I get the chance. I don't use Dart for web development, so I never test the JS output. I will need to find a way to profile the JS to see where the holdup is. This won't be a quick fix btw, sorry. Not sure when I will be able to provide a fix. But your concern is noted and I will work towards fixing it.

**Comment by Daegalus** [comment]
Actually, I would like to ask, are you using the default v4 or the cryptRNG v4? It will help me narrow down  the point of slowness.

**Comment by kostaa** [comment]
A bit more context to start with. I have noticed the issue while loading and converting the content of a file with 2,128 entries into Dart objects. Each object contains an UUID identifier so there are 2,128 UUIDs generated in the process. I used the plain v4() and also tried it with v1() which was a bit faster but the difference between the Dart and JavaScript was still substantial.  

In the meantime I have done a bit more experimenting and managed to speed it up now. The problem seems to be coming from the JavaScript constructor or whatever gets generated from the Dart constructor (have not looked into the generated code). The original code was like this 'String id = new Uuid().v1();' hence the Uuid constructor was called 2,128 times. 

I have removed the constructor from the loop now:

```javascript
  static Uuid UUID;
  static String generateUUID() {
    if (null == UUID) UUID = new Uuid();
    return UUID.v4();
  }
  String id = generateUUID();
```
This made the JavaScript code speed almost comparable with Dart and these are figures:  
  
UUID Version | Dart | JavaScript/Chrome | JavaScript/Firefox
------------ | ------------- | ------------- | -------------
v1 | 576 ms | 1,406 ms | 1,397 ms
v4 | 1,059 ms  | 5,996 ms | 8,885 ms

Regards,
Adam

**Comment by Daegalus** [comment]
Ah yes, you are only supposed to construct one instance of Uuid and then re-use the object for all your function use.

I will see if I can speed it up somehow. But there isn't much going on in v4 except for the sha function. using plain v4 just uses Math.Random() for random so it shouldn't be too slow either.

I'll take a look and see if I can improve the performance somwhere. Maybe I am creating too many things on the fly and should be re-using more myself.

I'll also try to read the generated JS to see if I something stupid is happening. Thanks for the additional context, it helps greatly.

**Comment by Daegalus** [comment]
Ok, I did some performance testing on the VM (not JS yet) and I can't seem to get your numbers. Here is my test code, and the outputs:

```dart
import 'lib/uuid.dart';

main() {
  var uuid = new Uuid();
  var startTime = new DateTime.now();

  var value = "";
  for (var i = 0; i < 2000000; i++) {
    value = uuid.v1();
  }

  var endTime = new DateTime.now();
  var diff = endTime.millisecondsSinceEpoch - startTime.millisecondsSinceEpoch;

  print("$diff ms");
}
```

My HTML for the JS output.
```html
<html>
<head>
    <title>Test</title>
</head>
<body>
 <p>hello world</p>
<script src="out.js" ></script>
</body>
```

These are the outputs I got:

version | git version | local optimization with reusing random in MathRNG | In Chrome as JS
----------|---------------|---------------------------------------------------------------------- | ----------------------
v1        |  840 ms    |  771 ms | 1482 ms
v4        |  1261 ms  | 1050 ms | 4001 ms

If you notice, I had to run the loop 2 million times to get close to the timings you are getting. I don't know if its computer performance difference, or how its being used, but if i did only 2000, I would get 16ms for every run on dart vm.

**Comment by kostaa** [comment]
This is down to my code running the file conversion as well so the UUID generation is only one part of it. 

To be honest with you once I took the constructor out of the loop the performance is fine so you do not need to spend more time on this.
