### ISSUE TITLE
uuid should be strong-mode clean

### ISSUE THREAD

**Issue by hterkelsen** [Daegalus/dart-uuid#20]
Any code that depends on uuid will not be [strong mode](https://github.com/dart-lang/dev_compiler/blob/master/STRONG_MODE.md) clean.

I've written a PR that adds the necessary type annotations to uuid to make it strong mode clean, please take a look: https://github.com/Daegalus/dart-uuid/pull/19

Thanks!

**Comment by Daegalus** [comment]
I merged the code, but had the following errors reported by Drone using v1.10

```
$ dart test/uuid_test.dart
00:00 +0: [Version 1 Tests] IDs created at same mSec are different
00:00 +1: [Version 1 Tests] Exception thrown when > 10K ids created in 1 ms
00:00 +2: [Version 1 Tests] Clock regression by msec increments the clockseq - mSec
00:00 +3: [Version 1 Tests] Clock regression by msec increments the clockseq - nSec
00:00 +4: [Version 1 Tests] Explicit options produce expected id
00:00 +5: [Version 1 Tests] Ids spanning 1ms boundary are 100ns apart
00:00 +6: [Version 4 Tests] Check if V4 is consistent using a static seed
00:00 +7: [Version 4 Tests] Return same output as entered for "random" option
00:00 +8: [Version 4 Tests] Make sure that really fast uuid.v4 doesn't produce duplicates
00:00 +9: [Version 5 Tests] Using URL namespace and custom name
'package:typed_data/typed_buffers.dart': error: line 175 pos 30: unexpected token '?'
    if (values is List) end ??= values.length;
```

I will fix it up when I get home, unless you get to it before I do.

**Comment by hterkelsen** [comment]
Looks like you need to update your drone.io to use Dart 1.12 or newer, which is where null-aware operators were introduced. I'm not sure how to update it.

**Comment by Daegalus** [comment]
Hmm, apparently its a problem with Drone, it wont go higher than 1.10, seems like I need to move to another CI system. Ill test it tonight locally on my home machine and push out a version.

Thanks again.

**Comment by hterkelsen** [comment]
On the Dart team we use Travis for CI. See https://github.com/dart-lang/dart2js_info/blob/master/.travis.yml for an example setup.

**Comment by Daegalus** [comment]
Ya, I'll do Travis. I used Drone back in the early days when Drone was the only one that supported Dart and I never switched away from it. I'll do that tonight.

**Comment by hterkelsen** [comment]
Awesome, thanks!

**Comment by Daegalus** [comment]
All set. 0.5.1 is pushed to Pub with your changed. Thanks again (tests passed locally on my 1.14 install). Ill go about switching to Travis CI. Closing this ticket.
