### ISSUE TITLE
Failed to install packet uuid under Windows 10

### ISSUE THREAD

**Issue by micrcx** [Daegalus/dart-uuid#23]
Failed to install packet uuid under Windows 10.
Running command "pub get" under the Windows 10 leads to message:

C:\Users\micrcx\IdeaProjects\TimerTest>pub get
Resolving dependencies...
Downloading crypto 0.9.2+1...
Downloading convert 1.1.1...
Failed to rename directory because access was denied.
This may be caused by a virus scanner or having a file
in the directory open in another application.

The package is not installed. In ubuntu everything works without problems. What's the matter?

File pubspec.yaml:

name: TimerTest
version: 0.0.1
description: A simple console application.
dependencies:
  uuid: 0.5.0

**Comment by Daegalus** [comment]
I recently switched to Windows, so I can test this later. I will look into it. At first glance, I don't know if this is a failure in UUID or in Pub on windows 10.

Are you using Command Prompt or Powershell? (so I can try to reproduce)

**Comment by micrcx** [comment]
I've used the command prompt. And two options: regular command prompt, and when failed, command prompt with the administrator privilege. The result is absolutely identical. Maybe can help additional information: I use IntelliJ IDEA 2016.3.4, Dart 1.22.

**Comment by micrcx** [comment]
I managed to solve the problem in a radical way. I just reinstalled Dart on my Windows 10 computer. After that all works fine as under ubuntu. Incidentally IntelliJ IDEA provides interface for using the pub tool instead of using the command line mode.
