### ISSUE TITLE
Eliminate uses of deprecated CONSTANTS

### ISSUE THREAD

**Issue by leafpetersen** [Daegalus/dart-uuid#24]
This package still uses deprecated Dart 1 SCREAMING CAPS CONSTANTS. These will be removed shortly in Dart 2. This rewriting tool can be used to automatically migrate code in most cases: https://github.com/dart-lang/dart2_fix .

**Comment by Daegalus** [comment]
Thanks for the heads up, I will get to this sometime today.

**Comment by leafpetersen** [comment]
Great, thanks!

**Comment by Daegalus** [comment]
All set, v1.0.1 released

**Comment by leafpetersen** [comment]
Thanks!
