### ISSUE TITLE
How to use one uuid multi times?

### ISSUE THREAD

**Issue by spartakos87** [Daegalus/dart-uuid#31]
How to use one uuid multi times?
I have a string 
  final String image_name = Uuid().v1.toString();
and every time I call image_name I take different value... How can I solve this?

**Comment by Daegalus** [comment]
You don't seem to be calling it like a function. You are missing parenthesis after the v1. And you don't need toString() as it already returns a string.

So this is what it should look like:
```
final String image_name = Uuid().v1()
```
