### ISSUE TITLE
Even though 2 UUID is "equal", it's hashcode is not

### ISSUE THREAD

**Issue by truongsinh** [Daegalus/dart-uuid#34]

**Comment by Daegalus** [comment]
a UUID object should never be equal, they have different seeds and such. And the functions will always return a byte list or string, so those are always easy to make equal. Hashcode should not be equal for a UUID object as the seed inside is always different every time you instantiate it. The only time they are equal is if all seeds and settings are identical between them, but even then its not necessary.
