### ISSUE TITLE
Move from `List<Int>` to `Uint8List`

### ISSUE THREAD

**Issue by truongsinh** [Daegalus/dart-uuid#35]
Ref: https://groups.google.com/a/dartlang.org/forum/#!topic/misc/JpNkRRLI9_w, https://github.com/dart-lang/protobuf/issues/219

More and more packages are explicitly switching to Uint8List.

**Comment by Daegalus** [comment]
Unnecessary change. Nothing I use returns Uint8list, its easy to convert between, and in the topic you linked, they say as much. If you need Uint8list, just convert it internally. I wont be changing this.
