### ISSUE TITLE
Can I generate uuid locally and make it unique for all my records

### ISSUE THREAD

**Issue by duomoteng** [Daegalus/dart-uuid#45]
Hi, I am a beginner in flutter and uuid. Assume that a uuid is generated by a users' mobile phone, and it needs to sync to the servers, where is saving many users' data. Can this package make the uuid unique for all the users' data on the servers.

**Comment by Daegalus** [comment]
Yes, it's what UUID is intended for. Universally unique ID. 

You generate the I'd, and save it to the database. If you need to recreate it, you need to save the random seed or just the UUID.

You can also save a username or email with the Id so you have an alternate way to look it up.

**Comment by duomoteng** [comment]
thanks!
