### ISSUE TITLE
Invalid UUIDv1

### ISSUE THREAD

**Issue by denis-evteev** [Daegalus/dart-uuid#47]
I’ve been using your package to generate UUIDs for some time without any issues, but today it generated the following v1 UUID: `134467e0-b6fe-11ea-d10f-5d81049d3983`. This is not a valid UUID, because the 4th block starts with `d`, indicating that this is a variant 2 UUID, which is “reserved, Microsoft Corporation backward compatibility” as defined in RFC.

I doubt that you intended to generate UUIDs reserved for backward compatibility, so there seems to be a bug in your implementation.

**Comment by Daegalus** [comment]
Thank you for reporting this, I will investigate later today. Sorry for the inconvenience, it definitely shouldn't happen as I only support v1, v4 and v5

**Comment by denis-evteev** [comment]
Thanks for an almost instant response. No worries so far, as my app is still in the dev stage.

**Comment by denis-evteev** [comment]
And yeah, this does look like a bug indeed. Here’s another one I got just now: `6f0cdbc0-b703-11ea-cb96-53164eea2c21`.

**Comment by Daegalus** [comment]
Ok, I looked up V2, the reason why this happens is because RFC4122 does not mention V2 outside of the bit layout for DCE and the Variant list. It also never mentions to not generate UUIDs that match V2, so i never wrote in protection from generating V2 style UUIDs. 

Ill look into fixing it that so it stops generating V2 uuids. Thanks for the heads up.

**Comment by denis-evteev** [comment]
Just to make sure that we’re both talking about the same thing, the issue that I described was not really related to UUID _version_. It was its _variant_ that seemed to be invalid.

I’m not a UUID expert, but if my understanding is correct, then a UUID _variant_ is encoded in the first character of the 4th block. Since three out of four variants defined in RFC are reserved, the only possible values corresponding to the remaining variant are `8..b`, while the generator returned UUIDs containing `d` and `c` at that place.

**Comment by Daegalus** [comment]
Yes, we are talking about the same thing, sorry. This is the code that does that: https://github.com/Daegalus/dart-uuid/blob/master/lib/uuid.dart#L181 so I am looking into why it is not setting it correctly. As this is how most UUID libraries set it, including the Reference code in the RFC

**Comment by denis-evteev** [comment]
Oh, that’s great then. It was the V2 thing that confused me.

**Comment by Daegalus** [comment]
Really sorry for the long delay, I had some RL shit to deal with. I pushed 2.2.0, this should fixed the issue. Looks like when I built this, I misread the spec and forgot to `& 0x3F00` the clock_high. The link above should show the new code. I added a test also.

**Comment by denis-evteev** [comment]
No problem. Thanks a lot for your effort!
