### ISSUE TITLE
Why options is a map?

### ISSUE THREAD

**Issue by Ascenio** [Daegalus/dart-uuid#49]
I was wondering why `options` are passed as a `Map<String, dynamic>` as it's not safer than a simple class.

**Comment by Daegalus** [comment]
No strong reason. Originally I was matching an existing Javascript library so people could migrate easier. I used dynamic maps for it. Now its mostly backwards compatibility and not breaking peoples code as many have it implemented using maps. Maybe once there is a need for another major version change, I can make the change to something more type safe and use a class.

**Comment by Ascenio** [comment]
You could migrate (in a future version) to make a version with objects and call it from the deprecated one (as well as marking it as such).
I think you could also delegate the algorithms of each version to match their corresponding class. 
```dart
// Before - the implementation
class UUid {
  String v1() { //... }
  String v4() { //... }
  String v5() { //... }
}

// Before - the client usage
var uuid = Uuid();
var options = <String, dynamic{
  // ...
};
final strUuid = uuid.v1(options);

// After - the implementation
abstract class UUIDBuilder {
  String build();
}
class V1Builder implements UUIDBuilder {}
class V4Builder implements UUIDBuilder {}

class Uuid {
  String call(UUIDBuilder builder) {
    return builder.build();
  }
  // ...
}
// After - the client usage
final builder = V4Builder()
    ..option1 = value
    ..option2 = value;
final strUuid = builder.build();
// or
final uuid = Uuid(builder);
final strUuid = builder.build();
```

**Comment by Daegalus** [comment]
I'll take this into consideration in the future. I'm not a fan of the builder pattern, but I'll definitely consider it when I'm implementing this.

A migration step with both functions (one map and one that takes classes) could be a good way to get migrations happening and marking deprecation.

**Comment by Ascenio** [comment]
Sure! Waiting to see improvements in future updates. Good luck :smile:
