### ISSUE TITLE
Parse from String to Uuid

### ISSUE THREAD

**Issue by morrowyn** [Daegalus/dart-uuid#52]
Hi, 

How would I parse a string `907b0976-00be-4465-9e00-a8f0d571979a` to a Uuid object using the library? I could only find the `parse(String)` but it returns a byte.

Regards,

**Comment by Daegalus** [comment]
There is no object. You parse it to a byte array and then do what you need with it. I don't provide any helper features for a uuid, since you can only get limited data from it anyway.

**Comment by morrowyn** [comment]
Ah, thanks. Are there any plans on creating an uuid object?

**Comment by Daegalus** [comment]
You are the first to request one, what information would you like in a UUID Object if I were to add one?

The only info it can provide is Version (1,4,5) and maybe Variant but no one really sets variants and uses random numbers for that too.

The rest is all random bits from the RNG source at time of creation.

**Comment by morrowyn** [comment]
I was more thinking on a specific value object, like datetime for instance, in the line of the following api's
Java UUID: https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html or 
C# Guid: https://docs.microsoft.com/en-us/dotnet/api/system.guid?view=net-5.0

**Comment by Daegalus** [comment]
ok, I think thats doable and a valid usecase. Give me a bit to add that. Currently focused on null safety stuff, But I can get our some of this stuff for you soon. I will most likely create new functions to do this, so that I don't break backwards compatibility for now.

**Comment by Daegalus** [comment]
made the changes in `3.0.0-nullsafety.1`, please give it a try and open a new ticket if its broken or other requests. It has a new `UuidValue` object, and appropriate functions.

**Comment by morrowyn** [comment]
Thanks a lot. I'm going to give it a go.

**Comment by polarby** [comment]
Why not merge `Uuid` and `UuidValue` as one Object? I see no point in creating an additional Object? Image `Uuid.v4() `would simply initialise the internal String uuid. You could work with static functions to do methods like `Uuid.parse()`...

**Comment by polarby** [comment]
Understandable. 

Only want to clarify the second point. I mean `Uuid.v4()` as an initializer rather than a function that can change whenever. `Uuid` would still be constant.

Anyway, thanks for the explanation!
