### ISSUE TITLE
Constant constructor

### ISSUE THREAD

**Issue by jaripekkala** [Daegalus/dart-uuid#55]
Hi, thanks for the package.

Any change of making the `Uuid` class constructor a constant?

We have a class that has a dependency to the `Uuid` and we would like to provide a default value for it (that must be a constant).

```dart
class MyClass {
  final Uuid uuid;

  MyClass([this.uuid = const Uuid()]);
}
```

**Comment by Daegalus** [comment]
Sorry for delay, been a busy day.

I have no problem doing this but I need to make sure it's not a breaking change. Or offer a separate constructor that's const so I don't break backwards compatibility.

I will look into it over the next few days

**Comment by Daegalus** [comment]
made the changes in `3.0.0-nullsafety.1`, please give it a try and open a new ticket if its broken or other requests.

**Comment by jaripekkala** [comment]
Thank you, @Daegalus! Much appreciated
