### ISSUE TITLE
parse() should fail for invalid UUIDs

### ISSUE THREAD

**Issue by sssilver** [Daegalus/dart-uuid#57]
Presently if you ask `parse()` to parse an invalid UUID, it'll just return a list of zeros.

This makes error handling bizarre. Failing to parse should result in an error, not a value.

**Comment by Daegalus** [comment]
Thanks for bringing this up. You are right, should return an error.

I'll provide a `validate` function. And then use it in parse before parsing.

I'm a bit swamped this week but I'll try to get to it soon.

**Comment by simolus3** [comment]
Maybe we could also make it throw an exception? We don't have a stable 3.0.0 release yet, so there's room for breaking changes and I think this would make the api more consistent.

**Comment by Daegalus** [comment]
made the changes in `3.0.0-nullsafety.1`, please give it a try and open a new ticket if its broken or other requests.

**Comment by sssilver** [comment]
I second @simolus3 's opinion here, error semantics in Dart are conveyed through extensions and the idiomatic thing to do in this case would be to throw one.

**Comment by Daegalus** [comment]
Makes sense. And this is a good time to do it. Well the latest nullsafety version throws exceptions. So that should cover this.
