### ISSUE TITLE
Compatibility issues when installed together with mqtt_client

### ISSUE THREAD

**Issue by mrdc** [Daegalus/dart-uuid#61]
Hello,

I’m experiencing this issue when trying to add the uuid package to my project:

```
Because uuid >=3.0.0 depends on crypto ^3.0.0 and mqtt_client >=6.2.0 depends on crypto ^2.1.3, uuid >=3.0.0 is incompatible with mqtt_client >=6.2.0.

So, because App depends on both mqtt_client ^8.0.0 and uuid 3.0.1, version solving failed.
```

**Comment by Daegalus** [comment]
You should pin to a version before 3.0.0 if you want to use libraries that aren't nullsafety supported yet. 

This library from 3.0.0 onward is nullsafety ready and needs it's dependencies to be nullsafety ready also. crypto 3.0.0 is the nullsafety version of crypto. So I can't go lower than that.

Open a issue with the mtqq library for it to update.

**Comment by mrdc** [comment]
Thanks!
