### ISSUE TITLE
Uuid validation is unable to validate certain types of Uuid

### ISSUE THREAD

**Issue by TabooSun** [Daegalus/dart-uuid#62]
I have a server running on Asp.Net Boilerplate and we are using its [SequentialGuidGenerator](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp/SequentialGuidGenerator.cs).

`Uuid.parse` is unable to correctly validate the Guid generated using `SequentialGuidDatabaseType.SqlServer`.

I am not familiar with Guid, is this intentionally done so in `dart-uuid`?

**Comment by Daegalus** [comment]
Technically it should work, as when I look up how to generate a UUID in in C# it uses the GUID library, but not sure if there is anything being set that is incompatible. GUIDs arent always compatible as Microsoft does some extra things that make could break compatibility with RFC standard. 

Can you give me an example of a non-working UUID so I can see what is breaking? I will do some digging on GUID implementation details to see if there is something special you need to do.

**Comment by TabooSun** [comment]
Here are some Guid that are not working:

- `87aa344e-6789-8180-976a-39fb5a323d65`
- `82e78cd0-c0cf-dd3f-cea9-39fb5a3545c5`
- `8b42fb8a-b511-f6b4-8257-39fb5a36007e`

**Comment by Daegalus** [comment]
Ya, that format is all wrong. For reference: https://en.wikipedia.org/wiki/Universally_unique_identifier#Format this is how UUID format works. The first thing that breaks is the version bit, the first character in the 3rd segment (after the 2nd dash) needs to be the UUID version. None of those are valid versions.

It looks like this GUID generator is generating weird GUIDs. Though the thing that is the 2nd worst offender is the order of data. `SqlServer` writes the random data in the beginning, and teh timestampt data at the end. UUID puts the timestamp in the beginning and random data at the end. This matches the `MySql` and `PostgreSQL` types better.

Not sure if you can change your database type, but that might fix the issue. I am not sure what the best way to fix this, as this is something custom to Microsoft. You can generate random GUIDs using NewGUID, but ti seems for UUID v1 you need to implement it yourself for the most part.

**Comment by TabooSun** [comment]
Is it possible to allow the `Uuid.parse` to skip the `isValidUUID`? Will this be a good idea?

**Comment by Daegalus** [comment]
Usually not a good idea, but maybe we can figure out a way to solve this 

Are you just using UUID.parse to convert from string to byte list?

If so, you can just copy the function into your dart code and remove the validation check. The function is self-contained and just relies on built in dart libraries.

What is your usecase, or what are you trying to accomplish?

**Comment by TabooSun** [comment]
Ya, I am using `Uuid.parse` as well as `UuidValue`. 

I would hope that this could be solved by this package itself, otherwise, I will need to keep track on your code and copy over whenever there is any enhancement or bugfix on the `Uuid.parse` method. As for the UuidValue, I would need to create my own copy of it and create an extension method to map from yours to mine (use case where I generate Uuid from `Uuid.v4obj`), which introduce extra complexity and unnecessity.

Could I suggest that we introduce an enum for validation? By using `Uuid.parse(uuid, validation: UuidValidation.guid)`.

Another suggestion would be introducing a dedicated class for Guid. Though I have no idea how much work this is needed to follow Guid's standard (e.g. Uppercase) or will this be out of scope of this project.

**Comment by Daegalus** [comment]
Those are all fair points. Give me a bit of time to think on this. The best solution is to make a GUID class or support tools and use any existing functions I have to make implementation easier. 

I just need to dig in and see where their spec is documented so I can implement it or see how I can make it work.

If not, I can add override parameters that disable the validation . Maybe I can do that sooner and then figure out GUID.

**Comment by TabooSun** [comment]
The validation disabling is much appreciated. Is there any ETA for this?

**Comment by Daegalus** [comment]
I'll try to get it to you tomorrow (US PDT - GMT-7), if not, I'll get it Saturday

**Comment by Daegalus** [comment]
ok, I have added an optional `validate` parameter for `parse` and `UuidValue` so that you can set it to false and skip validation. I already pushed 3.0.2 with the change.
