### ISSUE TITLE
App uses an insecure  Random Number Generator - issue mention in the scan report by MOBSF.

### ISSUE THREAD

**Issue by sanjaykumar-kiwitech** [Daegalus/dart-uuid#71]
App uses an insecure  Random Number Generator - issue mention in the scan report by MOBSF.

Please look in this.

**Comment by Daegalus** [comment]
I am aware, it's all over my documentation. If you want to use secure RNG, you need to set a certain variable to `UuidUtils.cryptoRNG`

I'm not sure what more is needed.
