### ISSUE TITLE
custom global grng is not working

### ISSUE THREAD

**Issue by Skycoder42** [Daegalus/dart-uuid#75]
Currently, the global options are ignored by Uuid class. The reason is simply, that data is incorrectly used in the `_init`methods:

```.dart
 void _initV4(Map<String, dynamic>? options) {
    options ??= {};

    // ...
  }
```

As you can see, the init method uses the *local* options, that have been passed into it via the `v4()` method, and not the global options of the constructor. This leads to global values like `grng` never beeing used!

**Comment by Daegalus** [comment]
Can you give me more information, because the stuff that handles grng is after this. Also `options ??= {};` doesnt do anything unless the options passed in are null, its just a null check with a default value.

```dart
void _initV4(Map<String, dynamic>? options) {
    options ??= {};


    if (!(_state['hasInitV4']! as bool)) {
      // Set the globalRNG function to mathRNG with the option to set an alternative globally
      var gPositionalArgs = (options['grngPositionalArgs'] != null)
          ? options['grngPositionalArgs']
          : [];
      var gNamedArgs = (options['grngNamedArgs'] != null)
          ? options['grngNamedArgs'] as Map<Symbol, dynamic>
          : const <Symbol, dynamic>{};


      final grng = options['grng'];
      _state['globalRNG'] = (grng != null)
          ? () => Function.apply(grng, gPositionalArgs, gNamedArgs)
          : UuidUtil.mathRNG;


      _state['hasInitV4'] = true;
    }
  }
```

I will do some testing though, and see if grng is being used properly. It seems I am missing a test for grng anyway.
