### ISSUE TITLE
The constructor being called isn't a const constructor.

### ISSUE THREAD

**Issue by ziakhan110** [daegalus/dart-uuid#86]
I am using version 4.0.0-beta1-1. I have this in the dependency_overrides: section , but now i am getting this error from external package.

```
Error: Non-redirecting const factory invocation is not a constant expression.
const _uuid = Uuid();
```

**Comment by Daegalus** [comment]
My apologies for the long delay. The email for this got sorted by a bad filter and I didn't notice it. Is this still a problem?

**Comment by ziakhan110** [comment]
I will check it

**Comment by PackRuble** [comment]
Same problem:
> Because no versions of share_plus match >6.3.1 <7.0.0 and share_plus 6.3.1 depends on share_plus_platform_interface ^3.2.0, share_plus ^6.3.1 requires share_plus_platform_interface ^3.2.0.
Because share_plus_platform_interface 3.2.0 depends on uuid ^3.0.6 and no versions of share_plus_platform_interface match >3.2.0 <4.0.0, share_plus_platform_interface ^3.2.0 requires uuid ^3.0.6.
Thus, share_plus ^6.3.1 requires uuid ^3.0.6.
So, because book_book depends on both share_plus ^6.3.1 and uuid ^4.0.0-beta1-1, version solving failed.

If I override the dependency, the following error occurs:
```text
/C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dev/share_plus_platform_interface-3.2.0/lib/method_channel/method_channel_share.dart:174:20: 
Error: Cannot invoke a non-'const' factory where a const expression is expected.
Try using a constructor or factory that is 'const'.
      const uuid = Uuid();
                   ^^^^
```

**Comment by daegalus** [comment]
Ok, it's 2am, so it's a bit late for me but just wanted to acknowledge that I saw your message and will start debugging tomorrow.

Sorry for the inconvenience.

**Comment by daegalus** [comment]
Ok, just published `4.0.0-beta2` be mindful of the changes, I had to make some to the constructors.

Let me know if it works for you now.

**Comment by PackRuble** [comment]
I use versions 4 and 7 and everything seems to be fine! You're just a magician :)

![image](https://user-images.githubusercontent.com/88033450/229041150-2e5f2292-3436-4335-a666-2e54758ab649.png)

**Comment by daegalus** [comment]
Awesome. I will close this issue then. Thank you for confirming. Please open a new issue if you encounter any problems.

**Comment by ziakhan110** [comment]
confirmed its fixed
