### ISSUE TITLE
is there a similar implementation to javas name UUID from bytes?

### ISSUE THREAD

**Issue by SebastianKlaiber** [daegalus/dart-uuid#93]
Hi, 

I'm trying to generate a UUID based on a String in the current version (native Android) the nameUUIDFromBytes function is used. And I need the exact UUID for the input values on flutter but unfortunately I get different results.

I tried UuidValue, Uuid.v5 

https://docs.oracle.com/javase/8/docs/api/java/util/UUID.html#nameUUIDFromBytes-byte:A-

Thanks for your support.

**Comment by daegalus** [comment]
Sorry for the delay. By the look of it, the Java library says `type 3` which is UUIDv3 based on `randomUUID` being `type 4` UUIDv4.

This library doesn't support UUIDv3 because we support UUIDv5 making UUIDv3 obsolete.
